### ISSUE TITLE
Use filters and/or search in the nested crud view

### ISSUE THREAD

**Issue by gabva** [onkbear/backpack-nested-crud#16]
Hi,

Wonderful feature, great job !

I just test it on a polymorphic one to many, it's working great

However i need to add search and filters in the nested crud list. I tried the backpack way but it's not showing.

Am I doing something wrong or is this feature not implemented yet ?

Thanks in advance

**Comment by onkbear** [comment]
Hi @gabva,

I am sorry but, both of search and filter functionalities are not implemented in the nested CRUD.
I could see it is not easy to implement them.
Please consider another way such as manipulating DOM in the list view.

Thank you.
