### ISSUE TITLE
Select2_from_ajax not working

### ISSUE THREAD

**Issue by PiahDoNeumann** [onkbear/backpack-nested-crud#19]
Hi, I am try to use select2_from_ajax, but not permit write text in the box and select listed items. See the code:

<pre>
        $this->crud->addField([
            'label'     => "Cód.Norma Referida",
            'type'      => 'select2_from_ajax',
            'name'      => 'cod_norma_referida',
            'entity'    => 'vinculoReferente',
            'attribute' => 'name',
            'data_source' => url("/get-select-data"),
            'placeholder' => 'Select option',
            'minimum_input_length' => 0,/*I try with 1,2,3,4,5...*/
            'method' => 'GET',
            'include_all_form_fields' => true, /*I try enable and disable*/
        ]);
</pre>

And the route:
<pre>
    Route::get('/get-select-data', [ NormaCrudController::class, 'getSelectData']);
</pre>

And the function getSelectData:
<pre>
    public function getSelectData(Request $request)
    {
        $search_term = $request->input('q');
        if ($search_term)
        {
            $results = Norma::select('name', 'id')->where('name', 'LIKE', '%'.$search_term.'%')->orderBy('id','asc')->paginate(10);
        }
        else
        {
            $results = Norma::select('name', 'id')->orderBy('id','asc')->paginate(10);
        }
        return $results;
    }
</pre>

**Comment by onkbear** [comment]
Hi @PiahDoNeumann,
Hmm... I have tested and it works for me.
Can you see any error logs on your browser console?
