### ISSUE TITLE
Migration to Backpack v5

### ISSUE THREAD

**Issue by PiahDoNeumann** [onkbear/backpack-nested-crud#20]
Hi, are you interested in migrating to backpack version 5?

**Comment by onkbear** [comment]
Hi @PiahDoNeumann,

The backpack/pro includes the inline relationship field, which is
almost the same functionality as this package.

https://backpackforlaravel.com/docs/5.x/crud-fields#manage-related-entries-in-the-same-form-create-update-delete

Therefore, this package is not necessary to be used Backpack v5 or later.
Do you think it makes sense?
