### ISSUE TITLE
Upload Field?

### ISSUE THREAD

**Issue by IsmailAshour** [onkbear/backpack-nested-crud#3]
There is a problem while using upload field in nested crud?

the file doesn't appear in the request.

could you please help ?

**Comment by IsmailAshour** [comment]
this because its not serialized in the post array, you can use Form data instead.

**Comment by onkbear** [comment]
Hi @drashoor,

Thank you for reporting.
You are right. I have fixed that using FormData instead.

Please update the package via `composer update`

Thanks,
