### ISSUE TITLE
Not working in Laravel 7.0

### ISSUE THREAD

**Issue by PiahDoNeumann** [onkbear/backpack-nested-crud#4]
Do you have any plans to upgrade to **Laravel 7.0**. It is giving error with "ajax" routes and the "nestedStore", it is saying that it is duplicated and do not let clear the cache of the routes "php artisan route: cache".

Message:
In AbstractRouteCollection.php line 210:
  Unable to prepare route [my-main-form/{id}/detail-form/ajax] for serialization. Another route has a
  lready been assigned name [detail-form.nestedStore].

**Comment by onkbear** [comment]
Hi @PiahDoNeumann,
Thank you for your reporting. I have fixed it.
Please update the package via composer update.

Thanks,
