### ISSUE TITLE
Not working in Laravel 7.0 - Translate Route

### ISSUE THREAD

**Issue by PiahDoNeumann** [onkbear/backpack-nested-crud#6]
I update to version 1.0.3 and show this message:

In AbstractRouteCollection.php line 210:
Unable to prepare route [admin/user/{user_id}/comment/ajax/{id}/translate/{lang}] for serialization. Another route has already been assigned name [comment.translateItem]. 

Thanks!

**Comment by onkbear** [comment]
Hi @PiahDoNeumann,
Sorry, I had not checked that route.
I have fixed it therefor, please update the package via composer update.

Thanks,

**Comment by PiahDoNeumann** [comment]
Thanks @onkbear
